// micro-frontends/dashboard/src/App.tsx
import { render, h } from "preact";

import "./index.scss";

const App = () => (
  <div class="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: dashboard</div>
    <div>Framework: preact</div>
    <div>Language: TypeScript</div>
    <div>CSS: Tailwind</div>
  </div>
);

render(<App />, document.getElementById("app"));

// micro-frontends/navigator/src/App.vue
<template>
  <div class="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: navigator</div>
    <div>Framework: vue3</div>
    <div>Language: TypeScript</div>
    <div>CSS: Tailwind</div>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from 'vue'

  export default defineComponent({});
</script>
